# all folders and files are relative to the path where fileb0x was run!

pkg = "static"
dest = "./static/"
fmt = true

# build tags for the main b0x.go file
tags = ""

# default: ab0x.go (so that its init() sorts first)
output = "ab0x.go"

[[custom]]
  # everything inside the folder
  # type: array of strings
  files = ["./dist/"]

  # base is the path that will be removed from all files' path
  # type: string
  base = ""

  # prefix is the path that will be added to all files' path
  # type: string
  prefix = ""
